use clap::Parser;
use codex_core::config::find_codex_home;
use std::io::{self, Write};

#[derive(Parser)]
pub struct InitCommand;

pub async fn run_init() -> ! {
    eprintln!("");
    eprintln!("  ⚡ Welcome to KV Code Setup!");
    eprintln!("");
    eprintln!("  This wizard will help you configure KV Code to use your AI provider.");
    eprintln!("");

    // Step 1: Choose provider
    eprintln!("  Step 1: Choose your AI provider");
    eprintln!("    1. DeepSeek (recommended - cheap & fast)");
    eprintln!("    2. OpenAI");
    eprintln!("    3. Kimi (moonshot.cn)");
    eprintln!("    4. Ollama (local)");
    eprintln!("    5. Custom (OpenAI-compatible API)");
    eprintln!("");

    let provider = read_line("  Enter your choice (1-5): ");

    let (provider_name, default_base_url, default_model) = match provider.trim() {
        "1" => ("deepseek", "https://api.deepseek.com", "deepseek-chat"),
        "2" => ("openai", "https://api.openai.com/v1", "gpt-4o-mini"),
        "3" => ("kimi", "https://api.moonshot.cn/v1", "kimi-k2.5"),
        "4" => ("ollama", "http://localhost:11434/v1", "llama3"),
        _ => {
            let name = read_line("  Enter provider name: ");
            let base_url = read_line("  Enter API base URL: ");
            let model = read_line("  Enter default model name: ");
            (name.trim(), base_url.trim(), model.trim())
        }
    };

    // Step 2: API key
    eprintln!("");
    eprintln!("  Step 2: Enter your API key");
    eprintln!("  (press Enter to skip if using Ollama/local)");
    let api_key = read_line("  API key: ");

    // Step 3: Generate config
    let codex_home: std::path::PathBuf = find_codex_home()
        .map(|p| p.into_path_buf())
        .unwrap_or_else(|_| {
            let home = std::env::var("HOME")
                .or_else(|_| std::env::var("USERPROFILE"))
                .map(std::path::PathBuf::from)
                .unwrap_or_else(|_| std::path::PathBuf::from("."));
            home.join(".kv-code")
        });

    std::fs::create_dir_all(&codex_home).ok();

    let config_path = codex_home.join("config.toml");
    let api_key_trimmed = api_key.trim();

    let config_content = format!(
        r#"# KV Code configuration
# Generated by `kv-code init`

[models]
"default" = "{default_model}"

[providers.{provider_name}]
type = "openai"
base_url = "{default_base_url}"
api_key = "{api_key_trimmed}"
"#
    );

    std::fs::write(&config_path, &config_content).ok();

    eprintln!("");
    eprintln!("  ✅ Configuration saved to:");
    eprintln!("     {}", config_path.display());
    eprintln!("");
    eprintln!("  You can now run: kv-code");
    eprintln!("");

    std::process::exit(0);
}

fn read_line(prompt: &str) -> String {
    print!("{prompt}");
    io::stdout().flush().ok();
    let mut line = String::new();
    io::stdin().read_line(&mut line).ok();
    line.trim().to_string()
}
