use clap::Parser;
use codex_core::config::find_codex_home;
use std::io::Write;
use std::io::{self};

#[derive(Debug, Parser)]
pub struct InitCommand;

pub async fn run_init() -> ! {
    eprintln!("");
    eprintln!("  ⚡ Welcome to KV Code Setup!");
    eprintln!("");
    eprintln!("  This wizard will help you configure KV Code to use your AI provider.");
    eprintln!("");

    // Step 1: Choose provider
    eprintln!("  Step 1: Choose your AI provider");
    eprintln!("    1. DeepSeek (recommended - cheap & fast)");
    eprintln!("    2. OpenAI");
    eprintln!("    3. Kimi (moonshot.cn)");
    eprintln!("    4. Ollama (local)");
    eprintln!("    5. Custom (OpenAI-compatible API)");
    eprintln!("");
    eprint!("  Enter your choice (1-5): ");
    io::stdout().flush().ok();
    let mut choice = String::new();
    io::stdin().read_line(&mut choice).ok();

    let provider_name: String;
    let default_base_url: String;
    let default_model: String;

    match choice.trim() {
        "1" => {
            provider_name = "deepseek".to_string();
            default_base_url = "https://api.deepseek.com".to_string();
            default_model = "deepseek-chat".to_string();
        }
        "2" => {
            provider_name = "openai".to_string();
            default_base_url = "https://api.openai.com/v1".to_string();
            default_model = "gpt-4o-mini".to_string();
        }
        "3" => {
            provider_name = "kimi".to_string();
            default_base_url = "https://api.moonshot.cn/v1".to_string();
            default_model = "kimi-k2.5".to_string();
        }
        "4" => {
            provider_name = "ollama".to_string();
            default_base_url = "http://localhost:11434/v1".to_string();
            default_model = "llama3".to_string();
        }
        _ => {
            eprint!("  Enter provider name: ");
            io::stdout().flush().ok();
            let mut n = String::new();
            io::stdin().read_line(&mut n).ok();
            provider_name = n.trim().to_string();

            eprint!("  Enter API base URL: ");
            io::stdout().flush().ok();
            let mut u = String::new();
            io::stdin().read_line(&mut u).ok();
            default_base_url = u.trim().to_string();

            eprint!("  Enter default model name: ");
            io::stdout().flush().ok();
            let mut m = String::new();
            io::stdin().read_line(&mut m).ok();
            default_model = m.trim().to_string();
        }
    }

    // Step 2: API key
    eprintln!("");
    eprintln!("  Step 2: Enter your API key");
    eprintln!("  (press Enter to skip if using Ollama/local)");
    eprint!("  API key: ");
    io::stdout().flush().ok();
    let mut api_key = String::new();
    io::stdin().read_line(&mut api_key).ok();
    let api_key = api_key.trim().to_string();

    // Step 3: Generate config
    let codex_home = find_codex_home()
        .map(|p| p.into_path_buf())
        .unwrap_or_else(|_| {
            let home = std::env::var("HOME")
                .or_else(|_| std::env::var("USERPROFILE"))
                .map(std::path::PathBuf::from)
                .unwrap_or_default();
            home.join(".config").join("codex")
        });

    std::fs::create_dir_all(&codex_home).ok();
    let config_path = codex_home.join("config.toml");

    let mut config_lines = vec![
        "# KV Code configuration".to_string(),
        "# Generated by `kv-code init`".to_string(),
        "".to_string(),
        "[models]".to_string(),
        format!("default = \"{default_model}\""),
        "".to_string(),
        format!("[model_providers.{provider_name}]"),
        "type = \"openai\"".to_string(),
        format!("base_url = \"{default_base_url}\""),
    ];

    if !api_key.is_empty() {
        config_lines.push(format!("api_key = \"{api_key}\""));
    }

    let config_content = config_lines.join("\n");
    std::fs::write(&config_path, &config_content).ok();

    eprintln!("");
    eprintln!("  ✅ Configuration saved to:");
    eprintln!("     {}", config_path.display());
    eprintln!("");
    eprintln!("  You can now run: kv-code");
    eprintln!("");

    std::process::exit(0);
}
